[[redirects]]
  from = "/ec/nasabudget"
  to = "https://web.archive.org/web/20240929144148/https://docs.google.com/spreadsheets/d/e/2PACX-1vTU9FhDV4U6X4suHtvoiMLYDN-y56ipoGh-N7n9fNq7BW1PiMsx5fVlj10LsgvTYVbu3CiUDO_WD0We/pubhtml#"
  status = 301
